packages:
  - "."

minimumReleaseAgeExclude:
  - "@chat-adapter/*"
  - "@ai-sdk/*"
  - "@vercel/*"
  - "@workflow/*"
  - eve
  - ai
  - chat
  - workflow
  - "@rolldown/*"
  - experimental-ai-sdk-code-mode
  - nitro
  - rolldown

allowBuilds:
  sharp: false
